//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_A2856B_edumatica100Entities : DbContext
    {
        public DB_A2856B_edumatica100Entities()
            : base("name=DB_A2856B_edumatica100Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<vGrafica> vGraficas { get; set; }
    
        [DbFunction("DB_A2856B_edumatica100Entities", "getEmpByCity")]
        public virtual IQueryable<getEmpByCity_Result> getEmpByCity(string ciudad)
        {
            var ciudadParameter = ciudad != null ?
                new ObjectParameter("Ciudad", ciudad) :
                new ObjectParameter("Ciudad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getEmpByCity_Result>("[DB_A2856B_edumatica100Entities].[getEmpByCity](@Ciudad)", ciudadParameter);
        }
    
        [DbFunction("DB_A2856B_edumatica100Entities", "getEmpByName")]
        public virtual IQueryable<getEmpByName_Result> getEmpByName(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getEmpByName_Result>("[DB_A2856B_edumatica100Entities].[getEmpByName](@Nombre)", nombreParameter);
        }
    }
}
