//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGrafica
    {
        public int ID { get; set; }
        public string NOM_DEP { get; set; }
        public Nullable<int> TOTAL { get; set; }
    }
}
